# Generated by Django 3.1.13 on 2021-09-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210907_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
